<?php if ($this->pageCount): ?>
    <ul class="pagination justify-content-center" style="margin:20px 0">
        <?php if (isset($this->previous)): ?>
        <li class="page-item">
        <?php else: ?>
        <li class="page-item disabled">
        <?php endif; ?>
            <a class="page-link" href="<?= $this->url($this->route, ['page' => $this->first]); ?>">
                First
            </a>
        </li>
        <?php if (isset($this->previous)): ?>
        <li class="page-item">
        <?php else: ?>
        <li class="page-item disabled">
            <?php endif; ?>
            <a class="page-link" href="<?= $this->url($this->route, ['page' => $this->previous]); ?>">
                &lt; Previous
            </a>
        </li>
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li class="page-item">
                <a class="page-link" href="<?= $this->url($this->route, ['page' => $page]); ?>">
                    <?= $page; ?>
                </a>
                </li>
            <?php else: ?>
                <li class="page-item active">
                <a class="page-link" href="<?= $this->url($this->route, ['page' => $page]); ?>">
                    <?= $page; ?>
                </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if (isset($this->next)): ?>
        <li class="page-item">
        <?php else: ?>
        <li class="page-item disabled">
            <?php endif; ?>
            <a class="page-link" href="<?= $this->url($this->route, ['page' => $this->next]); ?>">
                Next &gt;
            </a>
        </li>
        <?php if (isset($this->next)): ?>
        <li class="page-item">
            <?php else: ?>
        <li class="page-item disabled">
            <?php endif; ?>
            <a class="page-link" href="<?= $this->url($this->route, ['page' => $this->last]); ?>">
                Last
            </a>
        </li>
    </ul>
<?php endif; ?>