doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        #server_version: '5.7'
        #dbname: dummy
        #host: mysql
        #port: 3306
        #user: dummy
        #password: dummy
        #driver: mysqli

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\Traits:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/Traits'
                prefix: 'App\Entity\Traits'
                alias: App
