 
    version: '3'
     
    services:

        php:
            build:
                context: docker/php
                args:
                    TIMEZONE: ${TIMEZONE}
            ports:
                - 9000:9000
            volumes:
                - ./:/srv/www/api
                - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            environment:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}                
     
        nginx:
            image: nginx:1.13.8
            ports:
                - 80:80
            volumes:
                - ./:/srv/www/api
                - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            depends_on:
                - php

#        mysql:
#            image: mysql:5.7
#            ports:
#                - 3306:3306
#            depends_on:
#                - php
#            environment:
#                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#                MYSQL_DATABASE: ${MYSQL_DATABASE}
#                MYSQL_USER: ${MYSQL_USER}
#                MYSQL_PASSWORD: ${MYSQL_PASSWORD}

        beanstalkd:
            image: schickling/beanstalkd:latest
            restart: always
            ports:
                - "11300:11300"

#        redis:
#            image: redis:latest
#            ports:
#                - "6379:6379"
#            volumes_from:
#                - data

#        elasticsearch:
#            build: ./elasticsearch
#            volumes_from:
#                - data
#            ports:
#                - "9200:9200"
#                - "9300:9300"

#        dnsmasq:
#            image: andyshinn/dnsmasq:latest
#            restart: always
#            ports:
#                - "53535:53/tcp"
#                - "53535:53/udp"
#            cap_add:
#                - NET_ADMIN
#            command:
#                - "--address=/dev/127.0.0.1"

#        data:
#            image: cogniteev/echo
#            command: echo 'Data Container'
#            volumes:
#                - /var/lib/mysql
#                - /var/lib/redis
#                - /usr/share/elasticsearch/data
