    version: '3'
     
    services:
     
        php:
            build:
                context: docker/php
                args:
                    TIMEZONE: ${TIMEZONE}
            ports:
                - 9000:9000
            volumes:
                - ./:/srv/www/api
     
        nginx:
            image: nginx:1.13.8
            ports:
                - 80:80
            volumes:
                - ./:/srv/www/api
                - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            depends_on:
                - php